### PR TITLE
Added udev rule to control brightness of a offical RPI touch screen

### LINKED ISSUE #19: Add udev rule brightness in install script
To get the offical RPI touch screen working with the built-in brightness control there needs to be an udev rule set.

I propose to do this in the install.sh due it's specially written for the RPI. 
Will make an PR shortly for this.

Cheers,
Danny

### PR DESCRIPTION
**Pull request by dannybarake**
PR for issue #19

### CODE REVIEW

**Comment by rhysmorgan134** [comment]
I would add it as an argument, such as install.sh --touchrules, not everyone is using the pi screen, and the install script also works on other distros beside raspbian.

**Comment by robert5974** [comment]
That would work as well.  I was thinking of just a question at the beginning of the script if using the touchscreen.  The answer being the variable on which action to take.  Ignore versus implement.  Whatever is easy for you.

**Comment by dannybarake** [comment]
@rhysmorgan134 moved it to an seperate bash file. Maybe we can bundle the additional bash scripts in to 1 with all the options.

**Comment by dannybarake** [comment]
@rhysmorgan134 Already did it :-)

**Comment by rsjudka** [comment]
@dannybarake i like it, what do you mean by bundle then into 1 tho?

**Comment by dannybarake** [comment]
@rsjudka 1 bash script for additional install helpers. As you can see in the PR

**Pull request merged**
