### PR TITLE
Install overhaul

### LINKED ISSUE #63: Blackscreen on installation on raspi-os lite
# Issue

I've installed dash with the raspi-os lite image to reduce the overhead of pre-installed services / software.
When connecting my phone via USB Android auto loads on my phone but only displays a black screen in dash.

I've installed dash earlier with the full-blown raspi-os and it was working there.
It is running inside xinit under the pi user.
What am I missing?

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 3B 1GB | USB Cable         | Official Raspberry 7" Screen | Oneplus 5 | 6.2.610914-release          |

Installation Method: Install.sh

## Traceback (if applicable):
```bash
pi@raspberrypi:~ $ DISPLAY=:0 dash/bin/dash
libEGL warning: DRI2: failed to authenticate
[2021-04-15 23:42:23.730183] [0x70d63810] [info]    [Dash] [Bluetooth] Init
[2021-04-15 23:42:24.025504] [0x70d63810] [info]    [OpenAuto] [GSTVideoOutput] RPI Build, running with omxh264dec
[2021-04-15 23:42:24.056705] [0x70d63810] [info]    [OpenAuto] [AndroidBluetoothServer] listening.
[2021-04-15 23:42:24.080852] [0x70d63810] [info]    [OpenAuto] [btservice] Listening for connections, address: B8:27:EB:CA:9E:91, port: 22
[2021-04-15 23:42:24.084406] [0x70d63810] [info]    [OpenAuto] [btservice] Service registered, port: 22
[2021-04-15 23:42:24.084662] [0x70d63810] [info]    [OpenAuto] [btservice] Attempting to connect to last bluetooth device, 00:00:00:00:00:00 with `sudo stdbuf -oL rfcomm connect hci0 00:00:00:00:00:00 2
[2021-04-15 23:42:24.091686] [0x70d63810] [info]    [OpenAuto] [App] Waiting for USB device...
[2021-04-15 23:42:24.091958] [0x70d63810] [info]    [OpenAuto] [App] Waiting for Wireless device...
[2021-04-15 23:42:24.097568] [0x617732f0] [info]    [OpenAuto] [App] Devices enumeration result: false
[2021-04-15 23:42:24.535708] [0x70d63810] [info]    [Dash] [ELM327] Connecting elm disabled
[2021-04-15 23:42:24.536445] [0x70d63810] [info]    [Dash] [Gauges] Registered frame handler for id 2024
[2021-04-15 23:42:24.537009] [0x70d63810] [info]    [Dash] [Gauges] Registered frame handler for id 2024
[2021-04-15 23:42:24.537481] [0x70d63810] [info]    [Dash] [Gauges] Registered frame handler for id 2024
[2021-04-15 23:42:24.537965] [0x70d63810] [info]    [Dash] [Gauges] Registered frame handler for id 2024
[2021-04-15 23:42:25.103516] [0x70d63810] [info]    [OpenAuto] [GSTVideoOutput] Got resize request to 756x480
[2021-04-15 23:42:32.160176] [0x70d63810] [info]    [OpenAuto] [GSTVideoOutput] Got resize request to 748x480
[2021-04-15 23:42:32.300130] [0x70d63810] [info]    [Dash] [Bluetooth] Init complete!
[2021-04-15 23:42:32.300313] [0x70d63810] [info]    [Dash] [Bluetooth] Has Adapter: true, Has Media Device: false
[2021-04-15 23:42:39.017523] [0x617732f0] [info]    [OpenAuto] [App] USB Device connected.
[2021-04-15 23:42:39.027735] [0x70d63810] [debug]   [OpenAuto] [AudioInput] create.
[2021-04-15 23:42:39.042200] [0x70d63810] [debug]   [OpenAuto] [QtAudioOutput] create.
[2021-04-15 23:42:39.042622] [0x70d63810] [debug]   [OpenAuto] [QtAudioOutput] create.
[2021-04-15 23:42:39.043208] [0x70d63810] [debug]   [OpenAuto] [QtAudioOutput] create.
[2021-04-15 23:42:39.043900] [0x617732f0] [info]    [OpenAuto] [AndroidAutoEntity] start.
[2021-04-15 23:42:39.044377] [0x617732f0] [info]    [OpenAuto] [AudioInputService] start.
[2021-04-15 23:42:39.045057] [0x617732f0] [info]    [OpenAuto] [AudioService] start, channel: MEDIA_AUDIO
[2021-04-15 23:42:39.045445] [0x617732f0] [info]    [OpenAuto] [AudioService] start, channel: SPEECH_AUDIO
[2021-04-15 23:42:39.045662] [0x617732f0] [info]    [OpenAuto] [AudioService] start, channel: SYSTEM_AUDIO
[2021-04-15 23:42:39.045964] [0x617732f0] [info]    [OpenAuto] [SensorService] start.
[2021-04-15 23:42:39.046180] [0x617732f0] [info]    [OpenAuto] [VideoService] start.
[2021-04-15 23:42:39.046392] [0x617732f0] [info]    [OpenAuto] [BluetoothService] start.
[2021-04-15 23:42:39.046691] [0x617732f0] [info]    [AaSdk] [BluetoothServiceChannel] receive 
[2021-04-15 23:42:39.046915] [0x617732f0] [info]    [OpenAuto] [InputService] start.
[2021-04-15 23:42:39.302916] [0x607712f0] [info]    [OpenAuto] [AndroidAutoEntity] version response, version: 1.6, status: 0
[2021-04-15 23:42:39.302994] [0x607712f0] [info]    [OpenAuto] [AndroidAutoEntity] Begin handshake.
[2021-04-15 23:42:39.320140] [0x60f722f0] [info]    [OpenAuto] [AndroidAutoEntity] Handshake, size: 2282
[2021-04-15 23:42:39.340658] [0x60f722f0] [info]    [OpenAuto] [AndroidAutoEntity] continue handshake.
[2021-04-15 23:42:39.346646] [0x617732f0] [info]    [OpenAuto] [AndroidAutoEntity] Handshake, size: 51
[2021-04-15 23:42:39.347021] [0x617732f0] [info]    [OpenAuto] [AndroidAutoEntity] Auth completed.
[2021-04-15 23:42:39.351356] [0x60f722f0] [info]    [OpenAuto] [AndroidAutoEntity] Discovery request, device name: Android, brand: OnePlus ONEPLUS A5000
[2021-04-15 23:42:39.351465] [0x60f722f0] [info]    [OpenAuto] [AudioInputService] fill features.
[2021-04-15 23:42:39.351570] [0x60f722f0] [info]    [OpenAuto] [AudioService] fill features, channel: MEDIA_AUDIO
[2021-04-15 23:42:39.351623] [0x60f722f0] [info]    [OpenAuto] [AudioService] fill features, channel: SPEECH_AUDIO
[2021-04-15 23:42:39.351663] [0x60f722f0] [info]    [OpenAuto] [AudioService] fill features, channel: SYSTEM_AUDIO
[2021-04-15 23:42:39.351702] [0x60f722f0] [info]    [OpenAuto] [SensorService] fill features.
[2021-04-15 23:42:39.351756] [0x60f722f0] [info]    [OpenAuto] [VideoService] fill features.
[2021-04-15 23:42:39.351811] [0x60f722f0] [info]    [OpenAuto] [BluetoothService] fill features
[2021-04-15 23:42:39.351844] [0x60f722f0] [info]    [OpenAuto] [InputService] fill features.
[2021-04-15 23:42:39.467083] [0x617732f0] [info]    [OpenAuto] [AudioInputService] open request, priority: 0
[2021-04-15 23:42:39.467181] [0x617732f0] [info]    [OpenAuto] [AudioInputService] open status: 0
[2021-04-15 23:42:39.467726] [0x60f722f0] [info]    [OpenAuto] [AudioService] open request, channel: MEDIA_AUDIO, priority: 0
[2021-04-15 23:42:39.467809] [0x60f722f0] [debug]   [OpenAuto] [AudioService] channel: MEDIA_AUDIO audio output sample rate: 48000, sample size: 16, channel count: 2
[2021-04-15 23:42:39.467947] [0x60f722f0] [info]    [OpenAuto] [AudioService] open status: 0, channel: MEDIA_AUDIO
[2021-04-15 23:42:39.468012] [0x607712f0] [info]    [OpenAuto] [AudioService] open request, channel: SPEECH_AUDIO, priority: 0
[2021-04-15 23:42:39.468097] [0x607712f0] [debug]   [OpenAuto] [AudioService] channel: SPEECH_AUDIO audio output sample rate: 16000, sample size: 16, channel count: 1
[2021-04-15 23:42:39.468213] [0x607712f0] [info]    [OpenAuto] [AudioService] open status: 0, channel: SPEECH_AUDIO
[2021-04-15 23:42:39.468895] [0x607712f0] [info]    [OpenAuto] [AudioService] open request, channel: SYSTEM_AUDIO, priority: 0
[2021-04-15 23:42:39.469044] [0x607712f0] [debug]   [OpenAuto] [AudioService] channel: SYSTEM_AUDIO audio output sample rate: 16000, sample size: 16, channel count: 1
[2021-04-15 23:42:39.469317] [0x607712f0] [info]    [OpenAuto] [AudioService] open status: 0, channel: SYSTEM_AUDIO
[2021-04-15 23:42:39.469653] [0x60f722f0] [info]    [OpenAuto] [SensorService] open request, priority: 0
[2021-04-15 23:42:39.469759] [0x60f722f0] [info]    [OpenAuto] [SensorService] open status: 0
[2021-04-15 23:42:39.470616] [0x607712f0] [info]    [OpenAuto] [VideoService] open request, priority: 0
[2021-04-15 23:42:39.471166] [0x617732f0] [info]    [OpenAuto] [InputService] open request, priority: 0
[2021-04-15 23:42:39.471568] [0x617732f0] [info]    [OpenAuto] [InputService] open status: 0
[2021-04-15 23:42:39.472312] [0x61f742f0] [info]    [OpenAuto] [AudioService] setup request, channel: MEDIA_AUDIO, config index: 1
[2021-04-15 23:42:39.472432] [0x61f742f0] [info]    [OpenAuto] [AudioService] setup status: 2, channel: MEDIA_AUDIO
[2021-04-15 23:42:39.472690] [0x60f722f0] [info]    [OpenAuto] [AudioService] setup request, channel: SPEECH_AUDIO, config index: 1
[2021-04-15 23:42:39.473042] [0x60f722f0] [info]    [OpenAuto] [AudioService] setup status: 2, channel: SPEECH_AUDIO
[2021-04-15 23:42:39.473363] [0x61f742f0] [info]    [OpenAuto] [SensorService] sensor start request, type: 13
[2021-04-15 23:42:39.473802] [0x61f742f0] [info]    [OpenAuto] [AudioService] setup request, channel: SYSTEM_AUDIO, config index: 1
[2021-04-15 23:42:39.473882] [0x61f742f0] [info]    [OpenAuto] [AudioService] setup status: 2, channel: SYSTEM_AUDIO
[2021-04-15 23:42:39.475048] [0x61f742f0] [info]    [OpenAuto] [SensorService] sensor start request, type: 10
[2021-04-15 23:42:39.476061] [0x61f742f0] [info]    [OpenAuto] [InputService] binding request, scan codes count: 0
[2021-04-15 23:42:39.476495] [0x61f742f0] [info]    [OpenAuto] [InputDevice] start.
[2021-04-15 23:42:39.476911] [0x61f742f0] [info]    [OpenAuto] [InputService] binding request, status: 0
[2021-04-15 23:42:39.479225] [0x607712f0] [info]    [OpenAuto] [VideoService] open status: 0
[2021-04-15 23:42:39.480953] [0x61f742f0] [info]    [OpenAuto] [VideoService] setup request, config index: 3
[2021-04-15 23:42:39.481247] [0x61f742f0] [info]    [OpenAuto] [GSTVideoOutput] init
[2021-04-15 23:42:39.481610] [0x61f742f0] [info]    [OpenAuto] [VideoService] setup status: 2
[2021-04-15 23:42:39.482248] [0x617732f0] [info]    [OpenAuto] [VideoService] video focus indication.
[2021-04-15 23:42:39.485681] [0x607712f0] [info]    [OpenAuto] [VideoService] start indication, session: 0
[2021-04-15 23:42:39.939876] [0x70d63810] [info]    [OpenAuto] [GSTVideoOutput] Resizing to video container
[2021-04-15 23:42:41.057803] [0x70d63810] [info]    [OpenAuto] [GSTVideoOutput] Error Internal data stream error.
[2021-04-15 23:42:41.058503] [0x70d63810] [info]    [OpenAuto] [GSTVideoOutput] Error Internal data stream error.
```

### LINKED ISSUE #127: Support for Ubuntu 22.04
# Issue

Some changes are required to make this work with Ubuntu 22.04 on RPI. I've successfully hacked some things together to get it to work successfully, but I'd appreciate some advice from @rsjudka and @icecube45 as to the best way to actually implement these changes to avoid regressions. 

**First Issue - Install script line 25 doesn't detect debian version properly.**
On Ubuntu 22.04 /etc/debian_version simply contains "bookworm/sid" which breaks the install script as it doesn't properly read the version number, and therefore doesn't detect the changes needed in bullseye where qt5-default is missing from the repos. I'm not sure if there's a more universal approach to detecting the version so I think maybe searching the repos with `apt-cache search --names-only 'qt5-default'` and then adding the depencency if it's available may be a better approach?

**Second Issue - aasdk/src/Transport.SSLWrapper.cpp - set_FIPS_mode(0);**
Ubuntu 22.04 uses Openssl 3.0, which has removed the set_FIPS_mode() function. I've simply commented this line out, which I typically wouldn't feel comfortable doing, however this particular use is in a destructor so I don't think it breaks anything. Aasdk doesn't appear to set the fips mode anywhere else so I think this may be an acceptable fix.

**Third Issue - qt-gstreamer fails to build**
Ubuntu 22.04 uses libc 11 by default, which doesn't allow the second parameter of ‘__atomic_load’ to be volatile.
The fix I've used is to simply remove the volatile keyword from:
qt-gstreamer/elements/gstqtvideosink/gstqtvideosingplugin.h line 30
This could be implmented in another patch for qt-gstreamer.

**Fourth Issue - The dreaded whitescreen of death**
For some reason the "avdec_h264 " in openauto/openauto/Projection/GSTVideoOutput.cpp - line 61 doesn't work on Ubuntu 22.04. It's possible that it's missing from this distro version. I'm not sure of the best way to fix this without causing regressions but I do know how to make it work specifically for ubuntu 22.04. What I did was run "gst-inspect-1.0 | grep 264" and chose a decoder from the output. I used openh264dec, however I've noticed that v4l2h264dec is also a valid option here.
I think a possible solution would be to change the install script to basically do what I've done, run the gst-inspect-1.0 command and select the h264 decoder according to what's available on the system, instead of relying on the rpi define and then defaulting to avdec_h264 as it currently does. I'm not sure of the best way to pass this info to gstreamer. One option is to add some more defines for the specific decoders detected in the install script and defined in cmakelists, and use those to select the decoder in gstreamer, similar to what's already being done. Maybe there's a better decoder to default to? Some input here would definitely be appreciated.

### LINKED ISSUE #162: RasberryPi freezes during install
[ 83%] Building CXX object CMakeFiles/aasdk.dir/src/Channel/AV/AudioServiceChannel.cpp.o

RaspberryPi 3b+

### PR DESCRIPTION
**Pull request by breakingspell**
Various improvements and restructuring of the install process. Targeting Ubuntu 22.04 and Debian 12 (Raspberry Pi OS 2024-03).

DONE: 

- Address known build issues by including patches from https://github.com/openDsh/dash/pull/156/ (thanks!). Fixes https://github.com/openDsh/dash/issues/127 

- Identify exact RPi model, and advise remediation to prevent known OOM freeze on lower models. Fixes https://github.com/openDsh/dash/issues/162. 

- Ensure system apt package deps are correct (especially gstreamer and Xorg). Should fix https://github.com/openDsh/dash/issues/63 as well as automated Github Actions build/testing

- Collect all software deps checked out by install.sh into the dash project folder (some of these were being checked out to $HOME like aasdk, h264bitstream, gstreamer). This helps keep things manageable and tidy.

- Correct other script oddities (`sudo cat` failing when `sudo tee` works fine)

- Move all RPi and autostart enhancements from install.sh and src/bash/*.sh to `rpi.sh` and `autostart.sh`. Present usage at end of setup. 

- Provide an uninstall.sh to reverse linked `make install` and remove build folders.

Bonus idea: 

- Guide user through setting up wireless AA on RPi OS: nmcli and openauto.ini for hotspot, bluetoothctl and disable onboard BT via /boot/config.txt (This can be wiki page)

- Prompt or instruct user to apply potential whitescreen fix (RTAudio / `OutputBackendType=1` in openauto.ini). Not sure if this can be done before first execution (also can be noted on wiki)

**Related issue (if applicable):** fixes #<issue number goes here>
https://github.com/openDsh/dash/issues/63
https://github.com/openDsh/dash/issues/127
https://github.com/openDsh/dash/issues/162

### CODE REVIEW

**Comment by rsjudka** [comment]
i like the idea :+1: cant wait to see this merged in!

**Comment by breakingspell** [comment]
Getting close to done with the overhaul: compiles and executes on both my Pi 3 and 4 with no hitches outside of the resource pinch on the 3. AA connection to the phone works over USB and Wireless (haven't tested wireless on the 3).
 
The RPi autostart methods all work, system daemon and desktop icon assuming the default DE package `raspberrypi-ui-mods` is installed and set to autologin. I personally prefer the more minimal xinit method that only requires the Xorg base, seems to be the quickest startup too. 

I haven't tested the memory split or krnbt flags, they seem to be for even older boards than the 3. 
The GL module is a bit tricky, as it defaults to loading, and now the distinction seems to be between whether it uses real KMS or "fake" KMS, which also affects the display/brightness system.  

From here I need to test ofono/noise cancellation, then clean up and prettify parts that lack "echo" outputs and comments.

**Comment by parad0xnasha** [comment]
This has hit a brick wall at 46% - (Pi 4 1GB) Went unresponsive for about 20min, and ticked over to 47% at which 762MB/907MB RAM utilization at this point, and has entered another period of unresponsiveness (for at least the last 7min). The main branch would only make it to ~650MB utilization before freezing.
Was your testing performed on physical devices, or dev-environment-emulators? (dev-emulation seems to be a rather exhaustive workaround to compiling directly on the Pi).
I'm quite surprised that this issue took so long to be reported as an actual problem that needed addressing. Willing to assist in any manner possible in relation to this issue, if that would be of assistance.

**Comment by robert5974** [comment]
It has been tested on both physical and virtual.  Few questions for you,
what OS are you using? What is the error you received if any when it
freezes?  If there is no error, what is the last few lines of the install?

The installer was created and tested against Raspberry Pi OS 32-bit before
the 64-bit OS was released and on most models of the Rpi 3 and 4.  I don't
recall anyone using a pi4 1gb so perhaps that is an issue as there was a
portion that was different per model which we tried to capture every model
# in use.

It isn't. So much of a surprise that the install failed as it does all the
time depending on the board model, OS, package changes in the repos of the
different os versions.  There are many factors and we've dealt with them as
they come up.

Robert Crowley

**Comment by breakingspell** [comment]
Hello all, thanks for testing! To note, I have tested exclusively on Pi4 2GB and Pi3 1GB hardware with the same image (apart from an early VM test with 2GB RAM). I have a feeling the reason it's failing earlier on this branch is due to me raising the parallel make jobs (`-j4`). We may still need to lower this to -j2 for some packages.

I did find that raising swap space on the 1GB model to 1000M allowed it to finish the build, at the cost of long build time (over hour and a half on the Pi3 versus 25-30mins on Pi4 2GB). Without the extra memory, build would fail on the AASDK, qt-gstreamer, and Openauto builds, where qt-gstreamer seems to be the most resource intensive.  A few more details here: https://github.com/openDsh/dash/issues/162#issuecomment-2146881516. 

Also, wasn't aware they manufactured 1GB Pi4 models! The resource advisory at the start of the script filters out Pi4 and up, I need to remove that distinction so there's visibility on the memory requirements.

**Comment by parad0xnasha** [comment]
> It has been tested on both physical and virtual. Few questions for you, what OS are you using? What is the error you received if any when it freezes? If there is no error, what is the last few lines of the install? The installer was created and tested against Raspberry Pi OS 32-bit before the 64-bit OS was released and on most models of the Rpi 3 and 4. I don't recall anyone using a pi4 1gb so perhaps that is an issue as there was a portion that was different per model which we tried to capture every model # in use. It isn't. So much of a surprise that the install failed as it does all the time depending on the board model, OS, package changes in the repos of the different os versions. There are many factors and we've dealt with them as they come up. Robert Crowley

Much appreciated for the extremely prompt reply. Since posting this, i went looking at various other implementations, and it seems that a Pi 4 2GB is the bare minimum as the "accepted norm". This would explain the behaviour i'm seeing - I think it's swapping to SD REALLY REALLY slowly. I have chugged along to 52% now... I'd suggest a hardware requirement be set with a higher RAM level, but you initially approached this problem getting 3B+'s which also have 1GB across the line.

Knowing what i didn't know 24hrs ago, i'd purchase a Pi 4 4GB to approach this task. I'm going to purchase one, and happy to report back, but i suspect my SD-card is getting hammered to an inevitable demise! This is running latest Raspbian OS 64bit (Full desktop), and i did try the main branch with Raspbian Lite CLI also, which got me a little further than the GUI version. I feel like if i let this run for another 8hrs or so, I wouldn't be surprised if it does eventually complete. Just a matter of whether everything else stays running alongside it (it's continued to suffer repeated periods of non-responsiveness) - measured by the time on the clock - last update was 17min prior to current.

**Comment by robert5974** [comment]
For me, I always had trouble with adding the -j2 or -j4 so I always removed
it and just used the make command.  It worked every time without specifying
that.  It obviously took a longer time but I figured it was just my board
or something like that.  Perhaps it's worth a try.

Robert Crowley

**Comment by parad0xnasha** [comment]
> Hello all, thanks for testing! To note, I have tested exclusively on Pi4 2GB and Pi3 1GB hardware with the same image (apart from an early VM test with 2GB RAM). I have a feeling the reason it's failing earlier on this branch is due to me raising the parallel make jobs (`-j4`). We may still need to lower this to -j2 for some packages.
> 
> I did find that raising swap space on the 1GB model to 1000M allowed it to finish the build, at the cost of long build time (over hour and a half on the Pi3 versus 25-30mins on Pi4 2GB). Without the extra memory, build would fail on the AASDK, qt-gstreamer, and Openauto builds, where qt-gstreamer seems to be the most resource intensive. A few more details here: [#162 (comment)](https://github.com/openDsh/dash/issues/162#issuecomment-2146881516).
> 
> Also, wasn't aware they manufactured 1GB Pi4 models! The resource advisory at the start of the script filters out Pi4 and up, I need to remove that distinction so there's visibility on the memory requirements.
Well this would certainly explain the oversight! I'm glad i was able to provide something towards a resolution at least anyway!

> For me, I always had trouble with adding the -j2 or -j4 so I always removed it and just used the make command. It worked every time without specifying that. It obviously took a longer time but I figured it was just my board or something like that. Perhaps it's worth a try. Robert Crowley

For now i'll stick to the advice offered by the man himself, dropping the concurrent jobs AND increasing the swap space in order to at least get a feel for this dashboard solution, but i think the inevitable outcome would be using a 4GB Pi. I think you've checked off the box of PI integration issues now, and without seeing 1GB operating beside a 2GB/4GB, I can't say for certain, but it does seem that a minimum requirement suggestion be placed somewhere more prominent (not only as remnants of an issue that once upon a time on Github), but if it is indeed the case then it needs to be said loud enough to drown mention of lesser HW unless knowingly stepping into that arena, 
Personally i dont believe this to be a uniquely OpenDash problem. Only the  "thou shall not be named paid version" is the only software that sets hardware minimums, because they have to provide a level of service. Whereas OSS generally you want to reach as many users as possible... However, if i'd have known, given some indication prior to build/execution that ideally you want model X for smooth operation, i'd not have wasted the time and money. Project goes back onto pause now for me, until finances are such that i can freely purchase a 4gb, with little ROI - So i very well may consider abandoning the project, it's becoming much more than what i want/need, so i cant justify more costs. But yes, be nice if some people mentioned something about how troublesome 1GB devices can be, not just for this solution, but across the board

**Comment by breakingspell** [comment]
I've just learned that `make` without flags will default to using all available processing units it can (value returned with `nproc`, on both RPI 3 and 4 this is 4 threads), so the changes I made there are pretty useless. 
AASDK had -j2 set to begin with, but the rest can be default, I'll set them all back. 

> Only the "thou shall not be named paid version" is the only software that sets hardware minimums, because they have to provide a level of service. 

:joy: As a former user of said software, no comment. 
The only real thing I notice we're lacking now to be feature-equal is Equalizer (been testing pulseeffects in my car, it does "work" but it's all over the place, no gui controls etc)

**Comment by parad0xnasha** [comment]
> I've just learned that `make` without flags will default to using all available processing units it can (value returned with `nproc`, on both RPI 3 and 4 this is 4 threads), so the changes I made there are pretty useless. AASDK had -j2 set to begin with, but the rest can be default, I'll set them all back.

I assume this isn't very far from being merged into the openDsh/dash tree? Given the info learned, and potential hazards sufficiently handled

**Comment by parad0xnasha** [comment]
> 😂 As a former user of said software, no comment.

It was so moving, it put you onto a course of developing your own free alternative... Wow, i must really be in for a treat hahah!

Foolishly i purchased, so i'll give it a run, but it's unlikely to be the deployment choice. I should've dug deeper before making that terrible decision.

**Comment by breakingspell** [comment]
> I assume this isn't very far from being merged into the openDsh/dash tree? Given the info learned, and potential hazards sufficiently handled

Just pushed the branch here, it now excludes the -j flags except on AASDK as before. Will test it on my Pi3 real quick with the raised swap. 

I tested Ofono this weekend (was under the impression it was needed for Bluetooth HSF), and failing step is only for the noise cancellation module. Still need to write in the fix to insert the block into pulse config, and then write it into the uninstaller as well.

**Comment by rsjudka** [comment]
have been following along, just wanted to say appreciate all the work youve been putting in :raised_hands: 

like the direction this is going in

**Comment by breakingspell** [comment]
I'm glad I could help! Installer just needed a spruce-up, the core application works great. Making some last minute line and comment cleanups tonight as I test in a fast VM, I'll mark the PR as ready once it's done. 

It'll be tested on:
-Rpi4 2GB
-Ppi3 1GB+1GB swap
-Github Actions (Ubuntu 22.04)
-Base Ubuntu 22.04 Desktop VM (GNOME)

**Comment by robert5974** [comment]
I'll probably be testing on my Pi4 4gb.

Robert Crowley

**Comment by breakingspell** [comment]
Decided to move many of the "Rpi" options into an autostart.sh, they also work fine on the default Ubuntu desktop. rpi.sh only contains options specific to these units now.  The uninstaller should be safer and I eliminated usage of `cat` where I could per linting advice. Didn't change more than I had to, I left most existing comments and spacing alone.

Confirmed thee three autostart options work well in Ubuntu, and just xinit for the Pi image (no need to install full DE). 
USB udev rules work for Ubuntu as well, wired Android Auto launches without issue (wireless should work with configuration).

Huge push, but this should be the final one for now unless we come up with oddities in testing. :+1:

**Comment by robert5974** [comment]
Great work!  I put my Pi back together on a fresh new dash fascia and will be testing it out today or tomorrow.

**Comment by breakingspell** [comment]
Uh oh, so i'm not sure if it's my BT adapter, Bluez, Ofono, or Pulse:  turns out enabling Noise Cancellation causes the system to drop Handsfree calls 3 out of 4 times. 

With just `module-bluetooth-discover headset=ofono` in place, Handsfree works each time (and is required), it's `module-echo-cancel` that seems to have trouble. The times it does engage a call, there's no noticeable difference in call quality (recordings to myself on google voice with the tiny car mic). I had only tested it with two calls earlier this week on the road and got lucky. 

Before the setup overhaul, the noise cancellation step would fail due to shell permissions, so my system lacked that module all this time. My plan is to test picking and installing an older ofono version against the older pulseaudio (v12) to see if I can get both to work with no issues. If it's not clear, then I may consider commenting out the noise cancellation step until it's fixed.

**Comment by robert5974** [comment]
I was able to clone the repo last night and let it install with no changes
at all.  Great work!  I tested withPi4 2gb.  I have a 4gb model as well and
can probably test that as well but I'm not sure when I'll get the time
until next week.

Robert Crowley

**Comment by breakingspell** [comment]
One more small fix that I found today after driving on a fresh install: the xinit dependencies lacked `x11-xserver-utils` so `xset s noblank` wouldn't work without it. Quick push for that (squashed my commits way too early here :slightly_smiling_face: )

The Ofono component is much more confusing. I was under the impression that it was required for specific bluetooth handsfree modes on the Pi, but it looks like Pulse+Bluez are handling this: `backend-native` utilizes `a2dp_source` during media playback and `headset_audio_gateway` when on calls (the standard "PC" profile). This is noted in a relatively recent pull request: https://github.com/openDsh/openauto/pull/29. 

When Ofono is enabled in pulse config, I get output in dmesg like `Bluetooth: hci0: corrupted SCO packet`. Found that Ofono itself is a GSM telephony component that seems it was to be used with a concept phone frontend app for Dash. Can't find any other mentions of it on this repository (and I don't have a personal Slack account to check discussion there), so i'll set the install flag to false unless there's a reason to continue troubleshooting it. 

I can completely remove Ofono from the system and still make/receive calls inside wireless AA, so maybe HSP isn't necessary. Anyone else equipped to test handsfree calling with Wireless AA?

**Comment by rsjudka** [comment]
can't speak to ofono myself... if @icecube45 is around he might be able to say more about it 🙂

**Comment by TLMcNulty** [comment]
Didn't get an update from the user but https://github.com/openDsh/dash/issues/168 was closed working after reference to this branch.

**Comment by breakingspell** [comment]
Great to see that report knocked right out :grin: I'm not privvy to the discussion on Slack, are there any suggestions from that side? 

The only thing that kept me from saying that this is 100% ready to go: fully inspecting the uninstall.sh output from more than just a glance, making sure it actually removes only what was installed from the build and doesn't touch anything else. 

Just checked, every built dependency seems to properly live in `/usr/local` (for self compiled software), so that should be fine!

**Comment by TLMcNulty** [comment]
>Great to see that report knocked right out 😁 I'm not privvy to the discussion on Slack, are there any suggestions from that side?

Weirdly yes I believe. Removing ofono from the system has fixed handsfree calling for people, so yes, it might be best to remove it by default. 

I have a Pi 5 for the first time and I'm working out some kinks but I will update with testing results if/when I have some.

**Comment by breakingspell** [comment]
I also noticed this [recent Wiki page](https://github.com/openDsh/dash/wiki/Setting-up-hands%E2%80%90free-calling) highlight removing Ofono. It's settled then! 

Looking forward to the Pi 5 results

**Comment by TLMcNulty** [comment]
I have some issues on the 5 that I believe are unrelated to the work in this branch. Install works well and I'm in favor of merge.

**Comment by breakingspell** [comment]
I'm ready for merge too, if we missed something or there's an edge case, we can tackle it in a smaller PR.

**Comment by TLMcNulty** [comment]
I don't have any powers here so all we can do is say @icecube45 three times in the mirror.

**Comment by breakingspell** [comment]
I believe @rsjudka has merge permissions as well :grin: Thanks y'all!

**Comment by rsjudka** [comment]
love to see it :smiling_face_with_tear:

**Pull request merged**
